[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ceyal"
version = "0.1.0"
description = "A task management engine."
readme = "README.md"
requires-python = ">=3.14"
license = { text = "MIT" }
authors = [
    { name = "valrek_sol"}
]
dependencies = [
    "rich>=15.0.0",
    "dateparser>=1.4.0",
]

[project.scripts]
ceyal = "ceyal.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/ceyal"]
